### ISSUE TITLE
Problems with special characters in names

### ISSUE THREAD

**Issue by rfalkenstein** [studer-raimann/Panopto#5]
We just stumbled upon a 403 error for users whose name (here: lastname) contains special characters, in our case a single quote '. These users can open the tab "Content" but they can't open the tab "videos" of Panopto objects due to a Panopto 403 error. When tracking this down we came down to the class "class.xpanLTILaunch.php" https://github.com/fluxapps/Panopto/blob/main/classes/Videos/class.xpanLTILaunch.php which sets the different parameters for the LTI launch in $launch_data (https://github.com/fluxapps/Panopto/blob/297a9fa22ea1ee1a08fbb6eaf94bad55f6e894c2/classes/Videos/class.xpanLTILaunch.php#L26). In our case the problem came up with the name of "d'Origine". Upon replacing the single quote ' with nothing in line 31,32,33 https://github.com/fluxapps/Panopto/blob/297a9fa22ea1ee1a08fbb6eaf94bad55f6e894c2/classes/Videos/class.xpanLTILaunch.php#L32 via str_replace the call for the "videos" tab seems to work fine. The problem, however, is that we need to find a general solution if other special characters cause this problem, too. Do you have any idea?

**Comment by mstuder** [comment]
@rob0403  thanks for the describing the issue! @jheim2 thank you for your pull request!!
